### ISSUE TITLE
DeleteOnError does not seem to work (at least on Windows)

### ISSUE THREAD

**Issue by 030** [cavaliercoder/grab#45]
```
// create download request
req, err := NewRequest("", "http://example.com/example.zip")
if err != nil {
    panic(err)
}

// set request checksum
sum, err := hex.DecodeString("33daf4c03f86120fdfdc66bddf6bfff4661c7ca11c5da473e537f4d69b470e57")
if err != nil {
    panic(err)
}
req.SetChecksum(sha256.New(), sum, true)

// download and validate file
resp := DefaultClient.Do(req)
if err := resp.Err(); err != nil {
    panic(err)
}
```

Although there is a checksum mismatch, the file will not be removed:

```
panic: checksum mismatch

goroutine 1 [running]:
main.downloadOpenjdk()
        C:/Users/path/to/main.go:88 +0x1b6
main.main()
        C:/Users/path/to/main.go:94 +0x2c
exit status 2

```

Apart from this, how to prevent that the file gets downloaded anyway if there is checksum mismatch?

**Comment by cavaliercoder** [comment]
I agree, this error should be returned. Fixed this in c709a70. Please let me know if you can now see why your file was not deleted.

**Comment by cavaliercoder** [comment]
This may be because grab tries to delete the file before closing it (which does not manifest as an issue on Linux). I've refactored to ensure the file is first closed (see: 2c8601d).

Please test and advise.

**Comment by cavaliercoder** [comment]
@030 Any luck with this?

**Comment by cavaliercoder** [comment]
Thanks for the feedback :)
