### ISSUE TITLE
panic: test timed out after 10m0s

### ISSUE THREAD

**Issue by ghost** [cavaliercoder/grab#97]
Getting a panic on some long downloads, will dig into the code and see if I can come up with a solution as well.

panic: test timed out after 10m0s

goroutine 243 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000383520, {0x1a5393e?, 0x918e73ddc4774?}, 0x1d49410)
	/usr/local/go/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc0003e7e90?)
	/usr/local/go/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc000383520, 0xc00041fbd0)
	/usr/local/go/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0003e9900?, {0x25b8c40, 0x2e, 0x2e}, {0x0?, 0xc00038cf28?, 0x25d8ec0?})
	/usr/local/go/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0003e9900)
	/usr/local/go/src/testing/testing.go:1719 +0x5d9
github.com/XXXXXXXX/feeds.TestMain(0x1041311?)
	/Users/mfreeman/src/vulncheck/feeds/main_test.go:12 +0x2b
main.main()
	_testmain.go:141 +0x1d3

**Comment by ghost** [comment]
Closing, this was an issue with our test harness, fixed by go test -timeout 1200s
